
name: actions-fundamnetal
on:
  push:
    branches:
      - main
jobs: null
greet:
  runs-on: ubuntu-latest
steps:
  - name: say hello to users
    run: echo "Hello Brothers"
  - name: hello to username
    run: echo "Hello $USER"

